-- public.items definition

-- Drop table

-- DROP TABLE public.items;

CREATE TABLE public.items (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title varchar NOT NULL,
	price numeric NULL,
	weight int4 NULL,
	CONSTRAINT items_pk PRIMARY KEY (id)
);